### PR TITLE
Update worker-json.js

### PR DESCRIPTION
**Pull request by kailashgoswami**
getting invalid error message if array started with f,t or n.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
Could you show an example of json that was generating wrong error message before this change?

**Comment by Thartpart83** [comment]
Duplicate of #

**Comment by Thartpart83** [comment]
contriburting

**Review by Jaycas21 — APPROVED** [review]

**Comment by nightwing** [comment]
closing as json worker is replaced by  https://github.com/mkslanc/ace-linters now

**Pull request closed without merging**
