### PR TITLE
Remove file-loader from webpack-resolver

### PR DESCRIPTION
**Pull request by bumbummen99**
*Issue #, if available:*
ace-builds does not work without `file-loader` installed if webpack-resolver is being used.

*Description of changes:*
Changed webpack-resolver as explained in ajaxorg/ace#4744 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by antishov** [comment]
Hi, any updates on this?

**Comment by marcusds** [comment]
Any update on getting this merged in?

**Comment by nightwing** [comment]
Unfortunately this seems to break webpack 4, so we can't merge this directly, but we are adding esm loader which will work with all modern bundlers https://github.com/ajaxorg/ace/pull/5070

**Comment by nightwing** [comment]
the new esm-resolver is included in v1.15.3

**Pull request closed without merging**
